### ISSUE TITLE
File name issue with Upright

### ISSUE THREAD

**Issue by RosaWagner** [sovichet/kantumruy-pro#1]
@sovichet 
Currently working on onboarding these; "Upright" should be removed from the file name, for that you can remove it from the source name (designspace file), on which the binary file name is based.

**Comment by sovichet** [comment]
@RosaWagner
I have removed the "Upright" from the variable font binaries. Please check this commit https://github.com/sovichet/kantumruy-pro/commit/616348b40134e959d3c3df8a2b841435db347dff for the update.
